import Head from 'next/head'
import Image from 'next/image'
import Content from '../components/Content'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import requests from '../utils/requests'

// this component uses the props passed by the server side
export default function Home({results}) {
  
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <Content results={results}/>   
    </div>
  )
}

// this will pre-load the content in the server
export async function getServerSideProps(context){

  // this will get the value after "?genre=" in the url
  const genre = context.query.genre
  console.log(genre)

  // this will fetch in the API the corresponding url according to the genre
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || request.fetchTrending.url}`)
  .then(res => res.json())

  return {
    props: { // now it returns the result of the request. it will be used as props by the Home component
      results: request.results
    }
  }
}